server:
  port: 8088

# ??????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: wuhobin.pojo   #   ??
  mapper-locations: classpath:/mybatis/*.xml   #   xml??

logging:
  file:
    name: log/log.log
  level:
    root: info
    wuhobin: debug

